<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-06 09:29:51',
                'icon_class' => 'voyager-boat',
                'id' => 1,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.dashboard',
                'target' => '_self',
                'title' => 'Dashboard',
                'updated_at' => '2021-04-06 09:29:51',
                'url' => '',
            ),
            1 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-06 09:29:51',
                'icon_class' => 'voyager-images',
                'id' => 2,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.media.index',
                'target' => '_self',
                'title' => 'Media',
                'updated_at' => '2021-04-07 12:25:17',
                'url' => '',
            ),
            2 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-06 09:29:51',
                'icon_class' => 'voyager-person',
                'id' => 3,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.users.index',
                'target' => '_self',
                'title' => 'Users',
                'updated_at' => '2021-04-06 09:29:51',
                'url' => '',
            ),
            3 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-06 09:29:51',
                'icon_class' => 'voyager-lock',
                'id' => 4,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.roles.index',
                'target' => '_self',
                'title' => 'Roles',
                'updated_at' => '2021-04-06 09:29:51',
                'url' => '',
            ),
            4 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-06 09:29:51',
                'icon_class' => 'voyager-tools',
                'id' => 5,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Tools',
                'updated_at' => '2021-04-07 12:25:18',
                'url' => '',
            ),
            5 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-06 09:29:51',
                'icon_class' => 'voyager-list',
                'id' => 6,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.menus.index',
                'target' => '_self',
                'title' => 'Menu Builder',
                'updated_at' => '2021-04-07 12:25:18',
                'url' => '',
            ),
            6 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-06 09:29:51',
                'icon_class' => 'voyager-data',
                'id' => 7,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.database.index',
                'target' => '_self',
                'title' => 'Database',
                'updated_at' => '2021-04-07 12:25:18',
                'url' => '',
            ),
            7 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-06 09:29:51',
                'icon_class' => 'voyager-compass',
                'id' => 8,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.compass.index',
                'target' => '_self',
                'title' => 'Compass',
                'updated_at' => '2021-04-07 12:25:18',
                'url' => '',
            ),
            8 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-06 09:29:51',
                'icon_class' => 'voyager-bread',
                'id' => 9,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.bread.index',
                'target' => '_self',
                'title' => 'BREAD',
                'updated_at' => '2021-04-07 12:25:18',
                'url' => '',
            ),
            9 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-06 09:29:51',
                'icon_class' => 'voyager-settings',
                'id' => 10,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.settings.index',
                'target' => '_self',
                'title' => 'Settings',
                'updated_at' => '2021-04-07 12:25:18',
                'url' => '',
            ),
            10 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-06 09:29:52',
                'icon_class' => 'voyager-hook',
                'id' => 11,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.hooks',
                'target' => '_self',
                'title' => 'Hooks',
                'updated_at' => '2021-04-07 12:25:18',
                'url' => '',
            ),
            11 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-06 09:52:04',
                'icon_class' => 'voyager-search',
                'id' => 12,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.audits.index',
                'target' => '_self',
                'title' => 'Audits',
                'updated_at' => '2021-04-07 12:25:18',
                'url' => '',
            ),
            12 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-06 12:14:59',
                'icon_class' => 'voyager-documentation',
                'id' => 13,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.g-l-accounts.index',
                'target' => '_self',
                'title' => 'GL  Accounts',
                'updated_at' => '2021-04-07 12:25:18',
                'url' => '',
            ),
            13 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-07 06:04:56',
                'icon_class' => 'voyager-folder',
                'id' => 14,
                'menu_id' => 1,
                'order' => 9,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.g-l-sub-categories.index',
                'target' => '_self',
                'title' => 'GL  Sub Categories',
                'updated_at' => '2021-04-07 12:25:18',
                'url' => '',
            ),
            14 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-07 12:14:47',
                'icon_class' => 'voyager-folder',
                'id' => 15,
                'menu_id' => 1,
                'order' => 10,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.g-l-categories.index',
                'target' => '_self',
                'title' => 'GL  Categories',
                'updated_at' => '2021-04-07 12:25:18',
                'url' => '',
            ),
            15 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-07 12:22:29',
                'icon_class' => 'voyager-lock',
                'id' => 16,
                'menu_id' => 1,
                'order' => 11,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.permissions.index',
                'target' => '_self',
                'title' => 'Permissions',
                'updated_at' => '2021-04-07 12:25:18',
                'url' => '',
            ),
            16 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-04-07 12:23:47',
                'icon_class' => 'voyager-pie-chart',
                'id' => 17,
                'menu_id' => 1,
                'order' => 12,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Report',
                'updated_at' => '2021-04-07 12:25:20',
                'url' => '',
            ),
            17 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-04-07 12:25:05',
                'icon_class' => 'voyager-dollar',
                'id' => 18,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => '',
                'parent_id' => 17,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Profit & Loss',
                'updated_at' => '2021-04-11 13:44:16',
                'url' => 'pl_report',
            ),
            18 => 
            array (
                'color' => NULL,
                'created_at' => '2021-04-08 10:00:38',
                'icon_class' => 'voyager-news',
                'id' => 19,
                'menu_id' => 1,
                'order' => 13,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.report-types.index',
                'target' => '_self',
                'title' => 'Report Types',
                'updated_at' => '2021-04-08 10:00:38',
                'url' => '',
            ),
            19 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-04-10 09:38:11',
                'icon_class' => 'voyager-wallet',
                'id' => 20,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => '',
                'parent_id' => 17,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Balance Sheet',
                'updated_at' => '2021-04-11 13:44:25',
                'url' => 'bs_report',
            ),
        ));
        
        
    }
}